apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid-backend
  template:
    metadata:
      labels:
        app: covid-backend
    spec:
      containers:
      - name: covid-backend
        image: covid-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "sqlite:///covid.db"
---
apiVersion: v1
kind: Service
metadata:
  name: covid-backend-service
spec:
  selector:
    app: covid-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP