apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid-frontend
  template:
    metadata:
      labels:
        app: covid-frontend
    spec:
      containers:
      - name: covid-frontend
        image: covid-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://covid-backend-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: covid-frontend-service
spec:
  selector:
    app: covid-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer